export type TeethDentition = 'DECIDUOUS' | 'PERMANENT';
export type TeethArch = 'UPPER' | 'LOWER';
export type TeethSide = 'LEFT' | 'RIGHT';
export type TeethKind = 'INCISOR' | 'CANINE' | 'MOLAR' | 'PREMOLAR';

export type TeethDefinition = {
  code: string; // FDI (e.g. 51, 11)
  type: TeethDentition;
  arch: TeethArch;
  side: TeethSide;
  tooth_kind: TeethKind;
  name: string;
  name_th: string;
  order: number;
  start_occurrence_month: number;
  end_occurrence_month: number;
  start_destory_month?: number;
  end_destory_month?: number;
};

// Notes:
// - Ranges are approximate and intended for parent-facing guidance (not diagnosis).
// - Months are counted from birth.
const DECIDUOUS: TeethDefinition[] = [
  // Order (typical): central incisors → lateral incisors → first molars → canines → second molars
  // Upper Right (5x)
  {
    code: '51',
    type: 'DECIDUOUS',
    arch: 'UPPER',
    side: 'RIGHT',
    tooth_kind: 'INCISOR',
    name: 'Primary maxillary right central incisor',
    name_th: 'ฟันหน้าบนซี่กลาง (น้ำนม) ขวา',
    order: 2,
    start_occurrence_month: 8,
    end_occurrence_month: 12,
    start_destory_month: 72,
    end_destory_month: 96,
  },
  {
    code: '52',
    type: 'DECIDUOUS',
    arch: 'UPPER',
    side: 'RIGHT',
    tooth_kind: 'INCISOR',
    name: 'Primary maxillary right lateral incisor',
    name_th: 'ฟันหน้าบนซี่ข้าง (น้ำนม) ขวา',
    order: 4,
    start_occurrence_month: 9,
    end_occurrence_month: 13,
    start_destory_month: 84,
    end_destory_month: 108,
  },
  {
    code: '53',
    type: 'DECIDUOUS',
    arch: 'UPPER',
    side: 'RIGHT',
    tooth_kind: 'CANINE',
    name: 'Primary maxillary right canine',
    name_th: 'ฟันเขี้ยวบน (น้ำนม) ขวา',
    order: 7,
    start_occurrence_month: 16,
    end_occurrence_month: 22,
    start_destory_month: 120,
    end_destory_month: 144,
  },
  {
    code: '54',
    type: 'DECIDUOUS',
    arch: 'UPPER',
    side: 'RIGHT',
    tooth_kind: 'MOLAR',
    name: 'Primary maxillary right first molar',
    name_th: 'ฟันกรามน้ำนมซี่ที่ 1 บน ขวา',
    order: 6,
    start_occurrence_month: 13,
    end_occurrence_month: 19,
    start_destory_month: 108,
    end_destory_month: 132,
  },
  {
    code: '55',
    type: 'DECIDUOUS',
    arch: 'UPPER',
    side: 'RIGHT',
    tooth_kind: 'MOLAR',
    name: 'Primary maxillary right second molar',
    name_th: 'ฟันกรามน้ำนมซี่ที่ 2 บน ขวา',
    order: 9,
    start_occurrence_month: 25,
    end_occurrence_month: 33,
    start_destory_month: 120,
    end_destory_month: 156,
  },
  // Upper Left (6x)
  {
    code: '61',
    type: 'DECIDUOUS',
    arch: 'UPPER',
    side: 'LEFT',
    tooth_kind: 'INCISOR',
    name: 'Primary maxillary left central incisor',
    name_th: 'ฟันหน้าบนซี่กลาง (น้ำนม) ซ้าย',
    order: 2,
    start_occurrence_month: 8,
    end_occurrence_month: 12,
    start_destory_month: 72,
    end_destory_month: 96,
  },
  {
    code: '62',
    type: 'DECIDUOUS',
    arch: 'UPPER',
    side: 'LEFT',
    tooth_kind: 'INCISOR',
    name: 'Primary maxillary left lateral incisor',
    name_th: 'ฟันหน้าบนซี่ข้าง (น้ำนม) ซ้าย',
    order: 4,
    start_occurrence_month: 9,
    end_occurrence_month: 13,
    start_destory_month: 84,
    end_destory_month: 108,
  },
  {
    code: '63',
    type: 'DECIDUOUS',
    arch: 'UPPER',
    side: 'LEFT',
    tooth_kind: 'CANINE',
    name: 'Primary maxillary left canine',
    name_th: 'ฟันเขี้ยวบน (น้ำนม) ซ้าย',
    order: 7,
    start_occurrence_month: 16,
    end_occurrence_month: 22,
    start_destory_month: 120,
    end_destory_month: 144,
  },
  {
    code: '64',
    type: 'DECIDUOUS',
    arch: 'UPPER',
    side: 'LEFT',
    tooth_kind: 'MOLAR',
    name: 'Primary maxillary left first molar',
    name_th: 'ฟันกรามน้ำนมซี่ที่ 1 บน ซ้าย',
    order: 6,
    start_occurrence_month: 13,
    end_occurrence_month: 19,
    start_destory_month: 108,
    end_destory_month: 132,
  },
  {
    code: '65',
    type: 'DECIDUOUS',
    arch: 'UPPER',
    side: 'LEFT',
    tooth_kind: 'MOLAR',
    name: 'Primary maxillary left second molar',
    name_th: 'ฟันกรามน้ำนมซี่ที่ 2 บน ซ้าย',
    order: 9,
    start_occurrence_month: 25,
    end_occurrence_month: 33,
    start_destory_month: 120,
    end_destory_month: 156,
  },
  // Lower Left (7x)
  {
    code: '71',
    type: 'DECIDUOUS',
    arch: 'LOWER',
    side: 'LEFT',
    tooth_kind: 'INCISOR',
    name: 'Primary mandibular left central incisor',
    name_th: 'ฟันหน้าล่างซี่กลาง (น้ำนม) ซ้าย',
    order: 1,
    start_occurrence_month: 6,
    end_occurrence_month: 10,
    start_destory_month: 72,
    end_destory_month: 96,
  },
  {
    code: '72',
    type: 'DECIDUOUS',
    arch: 'LOWER',
    side: 'LEFT',
    tooth_kind: 'INCISOR',
    name: 'Primary mandibular left lateral incisor',
    name_th: 'ฟันหน้าล่างซี่ข้าง (น้ำนม) ซ้าย',
    order: 5,
    start_occurrence_month: 10,
    end_occurrence_month: 16,
    start_destory_month: 84,
    end_destory_month: 108,
  },
  {
    code: '73',
    type: 'DECIDUOUS',
    arch: 'LOWER',
    side: 'LEFT',
    tooth_kind: 'CANINE',
    name: 'Primary mandibular left canine',
    name_th: 'ฟันเขี้ยวล่าง (น้ำนม) ซ้าย',
    order: 8,
    start_occurrence_month: 17,
    end_occurrence_month: 23,
    start_destory_month: 108,
    end_destory_month: 132,
  },
  {
    code: '74',
    type: 'DECIDUOUS',
    arch: 'LOWER',
    side: 'LEFT',
    tooth_kind: 'MOLAR',
    name: 'Primary mandibular left first molar',
    name_th: 'ฟันกรามน้ำนมซี่ที่ 1 ล่าง ซ้าย',
    order: 6,
    start_occurrence_month: 14,
    end_occurrence_month: 18,
    start_destory_month: 108,
    end_destory_month: 132,
  },
  {
    code: '75',
    type: 'DECIDUOUS',
    arch: 'LOWER',
    side: 'LEFT',
    tooth_kind: 'MOLAR',
    name: 'Primary mandibular left second molar',
    name_th: 'ฟันกรามน้ำนมซี่ที่ 2 ล่าง ซ้าย',
    order: 10,
    start_occurrence_month: 23,
    end_occurrence_month: 31,
    start_destory_month: 120,
    end_destory_month: 156,
  },
  // Lower Right (8x)
  {
    code: '81',
    type: 'DECIDUOUS',
    arch: 'LOWER',
    side: 'RIGHT',
    tooth_kind: 'INCISOR',
    name: 'Primary mandibular right central incisor',
    name_th: 'ฟันหน้าล่างซี่กลาง (น้ำนม) ขวา',
    order: 1,
    start_occurrence_month: 6,
    end_occurrence_month: 10,
    start_destory_month: 72,
    end_destory_month: 96,
  },
  {
    code: '82',
    type: 'DECIDUOUS',
    arch: 'LOWER',
    side: 'RIGHT',
    tooth_kind: 'INCISOR',
    name: 'Primary mandibular right lateral incisor',
    name_th: 'ฟันหน้าล่างซี่ข้าง (น้ำนม) ขวา',
    order: 5,
    start_occurrence_month: 10,
    end_occurrence_month: 16,
    start_destory_month: 84,
    end_destory_month: 108,
  },
  {
    code: '83',
    type: 'DECIDUOUS',
    arch: 'LOWER',
    side: 'RIGHT',
    tooth_kind: 'CANINE',
    name: 'Primary mandibular right canine',
    name_th: 'ฟันเขี้ยวล่าง (น้ำนม) ขวา',
    order: 8,
    start_occurrence_month: 17,
    end_occurrence_month: 23,
    start_destory_month: 108,
    end_destory_month: 132,
  },
  {
    code: '84',
    type: 'DECIDUOUS',
    arch: 'LOWER',
    side: 'RIGHT',
    tooth_kind: 'MOLAR',
    name: 'Primary mandibular right first molar',
    name_th: 'ฟันกรามน้ำนมซี่ที่ 1 ล่าง ขวา',
    order: 6,
    start_occurrence_month: 14,
    end_occurrence_month: 18,
    start_destory_month: 108,
    end_destory_month: 132,
  },
  {
    code: '85',
    type: 'DECIDUOUS',
    arch: 'LOWER',
    side: 'RIGHT',
    tooth_kind: 'MOLAR',
    name: 'Primary mandibular right second molar',
    name_th: 'ฟันกรามน้ำนมซี่ที่ 2 ล่าง ขวา',
    order: 10,
    start_occurrence_month: 23,
    end_occurrence_month: 31,
    start_destory_month: 120,
    end_destory_month: 156,
  },
];

const PERMANENT: TeethDefinition[] = [
  // Typical order: first molars + incisors → premolars/canines → second molars → third molars
  // Upper Right (1x-8x)
  {
    code: '11',
    type: 'PERMANENT',
    arch: 'UPPER',
    side: 'RIGHT',
    tooth_kind: 'INCISOR',
    name: 'Permanent maxillary right central incisor',
    name_th: 'ฟันหน้าบนซี่กลาง (แท้) ขวา',
    order: 2,
    start_occurrence_month: 84,
    end_occurrence_month: 96,
  },
  {
    code: '12',
    type: 'PERMANENT',
    arch: 'UPPER',
    side: 'RIGHT',
    tooth_kind: 'INCISOR',
    name: 'Permanent maxillary right lateral incisor',
    name_th: 'ฟันหน้าบนซี่ข้าง (แท้) ขวา',
    order: 4,
    start_occurrence_month: 96,
    end_occurrence_month: 108,
  },
  {
    code: '13',
    type: 'PERMANENT',
    arch: 'UPPER',
    side: 'RIGHT',
    tooth_kind: 'CANINE',
    name: 'Permanent maxillary right canine',
    name_th: 'ฟันเขี้ยวบน (แท้) ขวา',
    order: 8,
    start_occurrence_month: 132,
    end_occurrence_month: 156,
  },
  {
    code: '14',
    type: 'PERMANENT',
    arch: 'UPPER',
    side: 'RIGHT',
    tooth_kind: 'PREMOLAR',
    name: 'Permanent maxillary right first premolar',
    name_th: 'ฟันกรามน้อยซี่ที่ 1 บน ขวา',
    order: 6,
    start_occurrence_month: 120,
    end_occurrence_month: 144,
  },
  {
    code: '15',
    type: 'PERMANENT',
    arch: 'UPPER',
    side: 'RIGHT',
    tooth_kind: 'PREMOLAR',
    name: 'Permanent maxillary right second premolar',
    name_th: 'ฟันกรามน้อยซี่ที่ 2 บน ขวา',
    order: 7,
    start_occurrence_month: 120,
    end_occurrence_month: 156,
  },
  {
    code: '16',
    type: 'PERMANENT',
    arch: 'UPPER',
    side: 'RIGHT',
    tooth_kind: 'MOLAR',
    name: 'Permanent maxillary right first molar',
    name_th: 'ฟันกรามแท้ซี่ที่ 1 บน ขวา',
    order: 1,
    start_occurrence_month: 72,
    end_occurrence_month: 84,
  },
  {
    code: '17',
    type: 'PERMANENT',
    arch: 'UPPER',
    side: 'RIGHT',
    tooth_kind: 'MOLAR',
    name: 'Permanent maxillary right second molar',
    name_th: 'ฟันกรามแท้ซี่ที่ 2 บน ขวา',
    order: 10,
    start_occurrence_month: 144,
    end_occurrence_month: 180,
  },
  {
    code: '18',
    type: 'PERMANENT',
    arch: 'UPPER',
    side: 'RIGHT',
    tooth_kind: 'MOLAR',
    name: 'Permanent maxillary right third molar (wisdom tooth)',
    name_th: 'ฟันกรามซี่ที่ 3 (ฟันคุด) บน ขวา',
    order: 12,
    start_occurrence_month: 204,
    end_occurrence_month: 264,
  },
  // Upper Left
  {
    code: '21',
    type: 'PERMANENT',
    arch: 'UPPER',
    side: 'LEFT',
    tooth_kind: 'INCISOR',
    name: 'Permanent maxillary left central incisor',
    name_th: 'ฟันหน้าบนซี่กลาง (แท้) ซ้าย',
    order: 2,
    start_occurrence_month: 84,
    end_occurrence_month: 96,
  },
  {
    code: '22',
    type: 'PERMANENT',
    arch: 'UPPER',
    side: 'LEFT',
    tooth_kind: 'INCISOR',
    name: 'Permanent maxillary left lateral incisor',
    name_th: 'ฟันหน้าบนซี่ข้าง (แท้) ซ้าย',
    order: 4,
    start_occurrence_month: 96,
    end_occurrence_month: 108,
  },
  {
    code: '23',
    type: 'PERMANENT',
    arch: 'UPPER',
    side: 'LEFT',
    tooth_kind: 'CANINE',
    name: 'Permanent maxillary left canine',
    name_th: 'ฟันเขี้ยวบน (แท้) ซ้าย',
    order: 8,
    start_occurrence_month: 132,
    end_occurrence_month: 156,
  },
  {
    code: '24',
    type: 'PERMANENT',
    arch: 'UPPER',
    side: 'LEFT',
    tooth_kind: 'PREMOLAR',
    name: 'Permanent maxillary left first premolar',
    name_th: 'ฟันกรามน้อยซี่ที่ 1 บน ซ้าย',
    order: 6,
    start_occurrence_month: 120,
    end_occurrence_month: 144,
  },
  {
    code: '25',
    type: 'PERMANENT',
    arch: 'UPPER',
    side: 'LEFT',
    tooth_kind: 'PREMOLAR',
    name: 'Permanent maxillary left second premolar',
    name_th: 'ฟันกรามน้อยซี่ที่ 2 บน ซ้าย',
    order: 7,
    start_occurrence_month: 120,
    end_occurrence_month: 156,
  },
  {
    code: '26',
    type: 'PERMANENT',
    arch: 'UPPER',
    side: 'LEFT',
    tooth_kind: 'MOLAR',
    name: 'Permanent maxillary left first molar',
    name_th: 'ฟันกรามแท้ซี่ที่ 1 บน ซ้าย',
    order: 1,
    start_occurrence_month: 72,
    end_occurrence_month: 84,
  },
  {
    code: '27',
    type: 'PERMANENT',
    arch: 'UPPER',
    side: 'LEFT',
    tooth_kind: 'MOLAR',
    name: 'Permanent maxillary left second molar',
    name_th: 'ฟันกรามแท้ซี่ที่ 2 บน ซ้าย',
    order: 10,
    start_occurrence_month: 144,
    end_occurrence_month: 180,
  },
  {
    code: '28',
    type: 'PERMANENT',
    arch: 'UPPER',
    side: 'LEFT',
    tooth_kind: 'MOLAR',
    name: 'Permanent maxillary left third molar (wisdom tooth)',
    name_th: 'ฟันกรามซี่ที่ 3 (ฟันคุด) บน ซ้าย',
    order: 12,
    start_occurrence_month: 204,
    end_occurrence_month: 264,
  },
  // Lower Left
  {
    code: '31',
    type: 'PERMANENT',
    arch: 'LOWER',
    side: 'LEFT',
    tooth_kind: 'INCISOR',
    name: 'Permanent mandibular left central incisor',
    name_th: 'ฟันหน้าล่างซี่กลาง (แท้) ซ้าย',
    order: 3,
    start_occurrence_month: 72,
    end_occurrence_month: 96,
  },
  {
    code: '32',
    type: 'PERMANENT',
    arch: 'LOWER',
    side: 'LEFT',
    tooth_kind: 'INCISOR',
    name: 'Permanent mandibular left lateral incisor',
    name_th: 'ฟันหน้าล่างซี่ข้าง (แท้) ซ้าย',
    order: 5,
    start_occurrence_month: 84,
    end_occurrence_month: 108,
  },
  {
    code: '33',
    type: 'PERMANENT',
    arch: 'LOWER',
    side: 'LEFT',
    tooth_kind: 'CANINE',
    name: 'Permanent mandibular left canine',
    name_th: 'ฟันเขี้ยวล่าง (แท้) ซ้าย',
    order: 9,
    start_occurrence_month: 108,
    end_occurrence_month: 132,
  },
  {
    code: '34',
    type: 'PERMANENT',
    arch: 'LOWER',
    side: 'LEFT',
    tooth_kind: 'PREMOLAR',
    name: 'Permanent mandibular left first premolar',
    name_th: 'ฟันกรามน้อยซี่ที่ 1 ล่าง ซ้าย',
    order: 6,
    start_occurrence_month: 120,
    end_occurrence_month: 144,
  },
  {
    code: '35',
    type: 'PERMANENT',
    arch: 'LOWER',
    side: 'LEFT',
    tooth_kind: 'PREMOLAR',
    name: 'Permanent mandibular left second premolar',
    name_th: 'ฟันกรามน้อยซี่ที่ 2 ล่าง ซ้าย',
    order: 7,
    start_occurrence_month: 132,
    end_occurrence_month: 156,
  },
  {
    code: '36',
    type: 'PERMANENT',
    arch: 'LOWER',
    side: 'LEFT',
    tooth_kind: 'MOLAR',
    name: 'Permanent mandibular left first molar',
    name_th: 'ฟันกรามแท้ซี่ที่ 1 ล่าง ซ้าย',
    order: 1,
    start_occurrence_month: 72,
    end_occurrence_month: 84,
  },
  {
    code: '37',
    type: 'PERMANENT',
    arch: 'LOWER',
    side: 'LEFT',
    tooth_kind: 'MOLAR',
    name: 'Permanent mandibular left second molar',
    name_th: 'ฟันกรามแท้ซี่ที่ 2 ล่าง ซ้าย',
    order: 11,
    start_occurrence_month: 132,
    end_occurrence_month: 180,
  },
  {
    code: '38',
    type: 'PERMANENT',
    arch: 'LOWER',
    side: 'LEFT',
    tooth_kind: 'MOLAR',
    name: 'Permanent mandibular left third molar (wisdom tooth)',
    name_th: 'ฟันกรามซี่ที่ 3 (ฟันคุด) ล่าง ซ้าย',
    order: 12,
    start_occurrence_month: 204,
    end_occurrence_month: 264,
  },
  // Lower Right
  {
    code: '41',
    type: 'PERMANENT',
    arch: 'LOWER',
    side: 'RIGHT',
    tooth_kind: 'INCISOR',
    name: 'Permanent mandibular right central incisor',
    name_th: 'ฟันหน้าล่างซี่กลาง (แท้) ขวา',
    order: 3,
    start_occurrence_month: 72,
    end_occurrence_month: 96,
  },
  {
    code: '42',
    type: 'PERMANENT',
    arch: 'LOWER',
    side: 'RIGHT',
    tooth_kind: 'INCISOR',
    name: 'Permanent mandibular right lateral incisor',
    name_th: 'ฟันหน้าล่างซี่ข้าง (แท้) ขวา',
    order: 5,
    start_occurrence_month: 84,
    end_occurrence_month: 108,
  },
  {
    code: '43',
    type: 'PERMANENT',
    arch: 'LOWER',
    side: 'RIGHT',
    tooth_kind: 'CANINE',
    name: 'Permanent mandibular right canine',
    name_th: 'ฟันเขี้ยวล่าง (แท้) ขวา',
    order: 9,
    start_occurrence_month: 108,
    end_occurrence_month: 132,
  },
  {
    code: '44',
    type: 'PERMANENT',
    arch: 'LOWER',
    side: 'RIGHT',
    tooth_kind: 'PREMOLAR',
    name: 'Permanent mandibular right first premolar',
    name_th: 'ฟันกรามน้อยซี่ที่ 1 ล่าง ขวา',
    order: 6,
    start_occurrence_month: 120,
    end_occurrence_month: 144,
  },
  {
    code: '45',
    type: 'PERMANENT',
    arch: 'LOWER',
    side: 'RIGHT',
    tooth_kind: 'PREMOLAR',
    name: 'Permanent mandibular right second premolar',
    name_th: 'ฟันกรามน้อยซี่ที่ 2 ล่าง ขวา',
    order: 7,
    start_occurrence_month: 132,
    end_occurrence_month: 156,
  },
  {
    code: '46',
    type: 'PERMANENT',
    arch: 'LOWER',
    side: 'RIGHT',
    tooth_kind: 'MOLAR',
    name: 'Permanent mandibular right first molar',
    name_th: 'ฟันกรามแท้ซี่ที่ 1 ล่าง ขวา',
    order: 1,
    start_occurrence_month: 72,
    end_occurrence_month: 84,
  },
  {
    code: '47',
    type: 'PERMANENT',
    arch: 'LOWER',
    side: 'RIGHT',
    tooth_kind: 'MOLAR',
    name: 'Permanent mandibular right second molar',
    name_th: 'ฟันกรามแท้ซี่ที่ 2 ล่าง ขวา',
    order: 11,
    start_occurrence_month: 132,
    end_occurrence_month: 180,
  },
  {
    code: '48',
    type: 'PERMANENT',
    arch: 'LOWER',
    side: 'RIGHT',
    tooth_kind: 'MOLAR',
    name: 'Permanent mandibular right third molar (wisdom tooth)',
    name_th: 'ฟันกรามซี่ที่ 3 (ฟันคุด) ล่าง ขวา',
    order: 12,
    start_occurrence_month: 204,
    end_occurrence_month: 264,
  },
];

export const TEETH_CATALOG: TeethDefinition[] = [...DECIDUOUS, ...PERMANENT];

export function getTeethCatalogByType(type: TeethDentition) {
  return TEETH_CATALOG.filter((t) => t.type === type).sort((a, b) => a.order - b.order);
}

